sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        custom:
                            -   isSystem: true
                                code: 'who-are-we'
                                items:
                                    -   highlighted: true
                                        translations:
                                            fr_FR:
                                                label: 'test'
                                    -   highlighted: false
                                        translations:
                                            fr_FR:
                                                label: 'new item'
                            -   isSystem: true
                                code: 'about-us'
                             
