sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        custom:
                            -   isSystem: true
                                createdAt: ~
                                updatedAt: ~
                                code: 'Who are we?'
                            -   isSystem: true
                                createdAt: ~
                                updatedAt: ~
                                code: 'About us'
                             
