sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        custom:
                            -   isSystem: true
                                code: 'main'
                                items:
                                    -   highlighted: true
                                        translations:
                                            en_EN:
                                                label: 'Who are we'
                                            fr_FR:
                                                label: 'Qui sommes nous'
                                    -   highlighted: false
                                        translations:
                                            en_EN:
                                                label: 'Que faisons nous'
                                            fr_FR:
                                                label: 'What we do'
                            -   isSystem: true
                                code: 'footer_legals'
                                items:
                                    -   highlighted: true
                                        translations:
                                            en_EN:
                                                label: 'resources'
                                            fr_FR:
                                                label: 'ressources'
                                    -   highlighted: false
                                        translations:
                                            en_EN:
                                                label: 'careers'
                                            fr_FR:
                                                label: 'carrières'
