sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        random: 3
                        custom:
                            -   isSystem: true
                                createdAt: ~
                                updatedAt: ~
                                code: 'salut'
                             
