sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        custom:
                            -   isSystem: true
                                code: 'main'
                                items:
                                    -   translations:
                                            en_EN:
                                                label: 'Dresses'
                                                url: '/en_US/taxons/category/dresses'
                                            fr_FR:
                                                label: 'Robes'
                                                url: '/fr_FR/taxons/category/dresses'
                                    -   translations:
                                            en_EN:
                                                label: 'Jeans'
                                                url: 'en_US/taxons/category/jeans'
                                            fr_FR:
                                                label: 'Jeans'
                                                url: 'fr_FR/taxons/category/jeans'
                            -   isSystem: true
                                code: 'footer_legals'
                                items:
                                    -   translations:
                                            en_EN:
                                                label: 'About'
                                                url: '#'
                                            fr_FR:
                                                label: 'A propos'
                                                url: '#'
                                    -   translations:
                                            en_EN:
                                                label: 'Terms and conditions'
                                                url: '#'
                                            fr_FR:
                                                label: 'Termes et conditions'
                                                url: '#'
