sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        custom:
                            -   isSystem: true
                                code: 'main'
                                items:
                                    -   translations:
                                            en_US:
                                                label: 'Dresses'
                                                url: 'taxons/category/dresses'
                                            fr_FR:
                                                label: 'Robes'
                                                url: 'taxons/category/dresses'
                                    -   translations:
                                            en_US:
                                                label: 'Jeans'
                                                url: 'taxons/category/jeans'
                                            fr_FR:
                                                label: 'Jeans'
                                                url: 'taxons/category/jeans'
                            -   isSystem: true
                                code: 'footer_legals'
                                items:
                                    -   translations:
                                            en_US:
                                                label: 'About'
                                                url: '#'
                                            fr_FR:
                                                label: 'A propos'
                                                url: '#'
                                    -   translations:
                                            en_US:
                                                label: 'Terms and conditions'
                                                url: '#'
                                            fr_FR:
                                                label: 'Termes et conditions'
                                                url: '#'
