sylius_grid:
    grids:
        monsieurbiz_menu_menu:
            driver:
                options:
                    class: '%monsieurbiz_menu.model.menu.class%'
            fields:
                code:
                    type: string
                    label: app.ui.code
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                        label: app.ui.create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                code:
                    type: string
                    label: app.ui.code
