imports:
    - { resource: "services.yaml" }
    - { resource: "sylius/resources.yaml" }
    - { resource: "sylius/grids.yaml" }
    - { resource: "sylius/ui.yaml" }
    - { resource: "sylius/fixtures.yaml"}
