MonsieurBiz\SyliusMenuPlugin\Entity\Menu\MenuItemTranslation:
    properties:
        label:
            -   NotBlank:
                    groups: [app]
            -   Length:
                    min: 2
                    max: 255
                    groups: [app]
        url:
            -   Valid: ~
